/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lib_sox_SoxJni */

#ifndef _Included_com_lib_sox_SoxJni
#define _Included_com_lib_sox_SoxJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lib_sox_SoxJni
 * Method:    addReverb
 * Signature: (Ljava/lang/String;Ljava/lang/String;IIIIII)V
 */
JNIEXPORT void JNICALL Java_com_lib_sox_SoxJni_addReverb
  (JNIEnv *, jclass, jstring, jstring, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_lib_sox_SoxJni
 * Method:    processBuffer
 * Signature: ([BI[BIIIIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_lib_sox_SoxJni_processBuffer
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint, jint, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
